#!/usr/bin/env python3
"""Publie en issue GitHub chaque chapitre nouvellement ajouté à chronicles/.

Appelé par le workflow .github/workflows/chapitre.yml après un push sur main.
Existe pour que la routine du MJ n'ait besoin d'aucun outil GitHub : elle écrit
et pousse des fichiers, la publication suit toute seule.

Les perceptions privées ne sont jamais ajoutées au corps de l'issue : elles sont
reprises depuis souls/<slug>/memory.md — où le MJ les a déjà écrites — et
postées en commentaire mentionnant le joueur concerné.
"""
import json
import re
import subprocess
import sys
from pathlib import Path


def gh(*args: str) -> str:
    return subprocess.run(["gh", *args], check=True, capture_output=True,
                          text=True).stdout.strip()


def titre_et_corps(chemin: Path) -> tuple[str, str]:
    lignes = chemin.read_text(encoding="utf-8").splitlines()
    titre = lignes[0].lstrip("# ").strip() if lignes else chemin.stem
    return titre, "\n".join(lignes[1:]).strip()


def tick_du_fichier(chemin: Path) -> int | None:
    m = re.search(r"(\d+)", chemin.stem)
    return int(m.group(1)) if m else None


def bloc_du_tick(memoire: Path, tick: int) -> str | None:
    """Extrait la section '## Tick N' de memory.md, si elle existe."""
    if not memoire.exists():
        return None
    texte = memoire.read_text(encoding="utf-8")
    m = re.search(rf"^## Tick {tick}\s*$(.*?)(?=^## |\Z)", texte,
                  flags=re.M | re.S)
    return m.group(1).strip() if m else None


FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


def main(fichiers: list[str]) -> int:
    joueurs = json.loads(Path("world/players.json").read_text(encoding="utf-8"))
    joueurs = [j for j in joueurs.get("players", []) if j.get("active")]

    for nom in fichiers:
        chemin = Path(nom)
        if not chemin.exists():
            print(f"ignoré (absent) : {nom}")
            continue

        titre, corps = titre_et_corps(chemin)
        url = gh("issue", "create", "--title", titre, "--body", corps + FOOTER)
        print(f"publié : {titre} → {url}")
        numero = url.rstrip("/").rsplit("/", 1)[-1]

        tick = tick_du_fichier(chemin)
        if tick is None:
            continue

        for j in joueurs:
            bloc = bloc_du_tick(Path("souls") / j["slug"] / "memory.md", tick)
            handle = j.get("github_handle")
            if not bloc or not handle:
                continue
            corps_commentaire = (
                f"@{handle} — ce que {j['mortal']} a vécu, perçu et cru "
                f"comprendre au chapitre {tick}. Lui seul le sait.\n\n"
                f"{bloc}{FOOTER}"
            )
            gh("issue", "comment", numero, "--body", corps_commentaire)
            print(f"  commentaire privé → @{handle}")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
